import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillInstagram,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "..//public/deved.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Aayush Kachhia</title>
        <meta name="description" content="Generated by create next app" />
      <link type="image/png" sizes="32x32" rel="icon" href="../public/icons8-xbox-a-office-m-32.png">
      </link>
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developed by aayush</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1xj1stqXq5Unh8M5wNAIKjIqzeLrU09zB/view?usp=sharing"
                  download="aayush_kachhia_resume.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Aayush Kachhia
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and designer .
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content
              needs. Join me down below and let&apos;s get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://twitter.com/KachhiaAayush" target="_blank" rel="noreferrer">
                <AiFillTwitterCircle />
              </a>
              <a
                href="https://www.linkedin.com/in/aayush-kachhia-866843249/"
                target="_blank"
                rel="noreferrer"
              >
                <AiFillLinkedin />
              </a>
              <a href="https://www.youtube.com/" target="_blank" rel="noreferrer">
                <AiFillYoutube />
              </a>
              <a
                href="https://www.instagram.com/aayush_kachhia/?hl=en"
                target="_blank"
                rel="noreferrer"
              >
                <AiFillInstagram />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image alt="image3" src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Graduate of computer science with experience working across the
              full-stack of software development. Looking for a role where I can
              grow and learn from experienced team members while drawing on
              project experience I have already successfully executed with many startups.
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I have learned React, Node.js, Java, C++, MongoDB, and a wide range of other skills, including brand design and marketing.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image alt="image2" src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Adobe XD</p>
              <p className="text-gray-800 py-1">Indesign</p>
              
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image alt="image1" src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let&apos;s make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Coding Language I Use</h4>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">React.js</p>+
              <p className="text-gray-800 py-1">C++</p>
              <p className="text-gray-800 py-1">python</p>
              <p className="text-gray-800 py-1">php</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image alt="image4" src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Technology</h3>
              <p className="py-2">
              I have extensive knowledge of technology and can assist with your current project. I&apos;m here to help enhance it.
              </p>
              <h4 className="py-4 text-teal-600">Technology  I know</h4>
              <p className="text-gray-800 py-1">NextJs</p>
              <p className="text-gray-800 py-1">Flutter</p>
              <p className="text-gray-800 py-1">Android</p>
              <p className="text-gray-800 py-1">Firebase</p>
              <p className="text-gray-800 py-1">MysqlDB</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I&apos;ve done remote work for
              <span className="text-teal-500"> agencies</span>, consulted for{" "}
              <span className="text-teal-500">startups</span>, and collaborated
              with talented people to create digital products for both business
              and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer a wide range of services, including brand design,
              programming and digital marketing .
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            For more information about my projects and <span className="text-teal-500"> portfolio </span> download my <span className="text-teal-500"> Resume</span> 
            </p>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              You can reach me at:{" "}
              <a
                href="mailto:aayushkachhia343@gmail.com"
                className="text-teal-500"
              >
                aayushkachhia343@gmail.com
              </a>
            </p>
          </div>

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          </div>
        </section>
      </main>
    </div>
  );
}
